server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false #缓冲的配置
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: /WEB-INF/views/
    suffix: .html

  #编码相关
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# kettle相关配置
kettle:
  filerepository:
   path: D:/SoftData/Kettle-repo/test
   id: kettleRepo
   name: kettleRepo
   description: 恩施kettle文件资源库
  log:
    level: basic  # 目前不考虑，对应nothing  error  minimal  basic  detailed  debug  rowlevel
    path: D:/log/kettle_log
